name: Build SmartDNS Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version of SmartDNS"
        required: true
      source_version:
        description: "Github commit hash to build"
        required: true

env:
  PKG_VERSION: ${{ github.event.inputs.version }}
  PKG_SOURCE_VERSION: ${{ github.event.inputs.source_version }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openwrt-sdk:
          - rockchip-armv8-21.02-SNAPSHOT

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Replace Version
        run: |
          cd smartdns/package/openwrt
          sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=$PKG_VERSION/g" Makefile
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$PKG_SOURCE_VERSION/g" Makefile
          sed -i "s/PKG_MIRROR_HASH:=.*//g" Makefile
          cat Makefile

      - name: Build SmartDNS
        run: |
          docker run -v "$PWD/build/bin:/home/build/openwrt/bin:Z" \
                     -v "$PWD/build/sdk-build.sh:/home/build/openwrt/sdk-build.sh" \
                     -v "$PWD/smartdns/package/openwrt:/home/build/openwrt/package/smartdns" \
                    openwrtorg/sdk:${{ matrix.openwrt-sdk }} /bin/bash /home/build/openwrt/sdk-build.sh

      - name: Find Package
        id: find_package
        run: |
          ipk_path=`find build/bin -name 'smartdns_*.ipk`
          if [[ -z "$ipk_path" ]]; then
            echo "::error title=Find IPK::Couldn't find smartdns ipk"
            exit 1
          fi
          echo "::set-output name=ipk_path::$ipk_path"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.find_package.outputs.ipk_path }}
