name: Build SmartDNS Release
on:
  workflow_dispatch:
    inputs:
      sdk_image_name:
        description: "OpenWRT SDK image name"
        required: true
        default: "rockchip-armv8-21.02-SNAPSHOT"

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone Makefile
        run: |
          svn co https://github.com/openwrt/packages/trunk/net/smartdns

      - name: Build SmartDNS ${{ github.event.inputs.sdk_image_name }}
        run: |
          docker run -v "$PWD/build/bin:/home/build/openwrt/bin:Z" \
                     -v "$PWD/build/sdk-build.sh:/home/build/openwrt/sdk-build.sh" \
                     -v "$PWD/smartdns:/home/build/openwrt/package/smartdns" \
                    openwrtorg/sdk:${{ github.event.inputs.sdk_image_name }} /bin/bash /home/build/openwrt/sdk-build.sh

      - name: Find Package
        id: find_package
        run: |
          ipk_path=`find build/bin -name 'smartdns_*.ipk'`
          if [[ -z "$ipk_path" ]]; then
            echo "::error title=Find IPK::Couldn't find smartdns ipk"
            exit 1
          fi
          echo "::set-output name=ipk_path::$ipk_path"
          echo "::set-output name=ipk_name::$(basename $ipk_path)"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.find_package.outputs.ipk_name }}
          path: ${{ steps.find_package.outputs.ipk_path }}
